### Simple Chat
GET http://localhost:8080/augmented-duke/ai/chat
Content-Type: text/plain
###

### Memory 1
GET http://localhost:8080/augmented-duke/ai/memory
Content-Type: text/plain
###

### Memory 2
GET http://localhost:8080/augmented-duke/ai/memory/more
Content-Type: text/plain
###
