# OpenAI configuration
dev.langchain4j.cdi.plugin.chat-model.class=dev.langchain4j.model.openai.OpenAiChatModel
dev.langchain4j.cdi.plugin.chat-model.config.api-key=${OPENAI_API_KEY}
dev.langchain4j.cdi.plugin.chat-model.config.model-name=gpt-5

dev.langchain4j.cdi.plugin.simple-memory.class=dev.langchain4j.memory.chat.MessageWindowChatMemory
dev.langchain4j.cdi.plugin.simple-memory.scope=jakarta.enterprise.context.SessionScoped
dev.langchain4j.cdi.plugin.simple-memory.config.maxMessages=10

